<?php
/**
 * TL_ROOT/system/modules/ce-access/languages/it/tl_user.php 
 * 
 * Contao extension: ce-access 1.1.4 stable 
 * Italian translation file 
 * 
 * Copyright : © 2008-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['contentelements']['0'] = "Elementi di contenuto disabilitati";
$GLOBALS['TL_LANG']['tl_user']['contentelements']['1'] = "Selezionare gli elementi di contenuto da disabilitare";
 
?>
