<?php
/**
 * TL_ROOT/system/modules/lessphp/languages/de/modules.php 
 * 
 * Contao extension: lessphp 0.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2013 David Enke, Leaf Corcoran 
 * License   : LGPL 
 * Author    : develab (david.enke), www.davidenke.de 
 * Translator: David Enke (david.enke), www.davidenke.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['lessphp']['0'] = "PHP LESS Kompilierer";
$GLOBALS['TL_LANG']['MOD']['lessphp']['1'] = "Bereitstellung und Implementierung von lessphp für Contao 3.";
 
?>
