<?php
/**
 * TL_ROOT/system/modules/lessphp/languages/de/tl_settings.php 
 * 
 * Contao extension: lessphp 0.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2013 David Enke, Leaf Corcoran 
 * License   : LGPL 
 * Author    : develab (david.enke), www.davidenke.de 
 * Translator: David Enke (david.enke), www.davidenke.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['checkedCompile']['0'] = "Kontrollierte Less-Kompilierung";
$GLOBALS['TL_LANG']['tl_settings']['checkedCompile']['1'] = "Die compileChecked-Methode kompiliert nur, wenn die Quelldatei neuer ist, oder die Zieldatei nicht existiert.";
 
?>
