<?php
/**
 * TL_ROOT/system/modules/backend_user_online/languages/lv/modules.php 
 * 
 * Contao extension: backend_user_online 3.0.0 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2007..2013 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['backend_user_online']['0'] = "BackendUserOnline";
$GLOBALS['TL_LANG']['MOD']['backend_user_online']['1'] = "Tiešsaistes statusa ikona gan lietotājiem, gan biedriem";
 
?>
